export * as authAPI from "./auth";
export * as categoriesAPI from "./categories";
export * as dishesAPI from "./dishes";
export * as cartAPI from "./cart";
export * as userAPI from "./user";
export * as paymentAPI from "./payment";
export * as promoAPI from "./promo";
export * as contactAPI from "./contact";
export * as ordersAPI from "./orders";